### ISSUE TITLE
Type Error: Cannot create property 'context' on String

### ISSUE THREAD

**Issue by shahzadbacha** [ibesora/vt-optimizer#11]
Hi,

I have been exploring vt-optimizer for inspecting vector tiles and it did give me a useful insight on my mbtiles, generated with tippecanoe (https://github.com/mapbox/tippecanoe). 

When i try to run it for possible optimizations, using the below command;

`node --max-old-space-size=66386 index.js -m pois.mbtiles -s style.json -o files/wikipedia_v2.mbtiles
`

it gives me the following error;

![image](https://user-images.githubusercontent.com/16791779/124653354-a2b33600-deb6-11eb-8770-49b936c95be8.png)

**Comment by ibesora** [comment]
Can you provide the mbtile file you are using? I'd love to take a closer look at the internal structure of it.

**Comment by shahzadbacha** [comment]
Sure, please have a look at the attached file.

[natural_earth.zip](https://github.com/ibesora/vt-optimizer/files/6774552/natural_earth.zip)

**Comment by shahzadbacha** [comment]
Hey @ibesora, did you find the time to look into the structure of the data?

**Comment by ibesora** [comment]
Yup, sorry for not answering before.
All the mbtiles I've seen until now have a `images` table where all the data is stored. Yours has a `tiles` table instead.
I'm working on a fix but unfortunately I'm leaving for 15 days tomorrow and I won't have my computer with me so I won't be able to work on this. If I can finish it today I will ping you but I'm not sure I will be able. Sorry

**Comment by ibesora** [comment]
Ok, I've just pushed some changes that should fix this.
I've tried your `natural_earth` mbtile with a style I had and it worked.
Can you please download the updated version and check if it works?
Thanks!

**Comment by shahzadbacha** [comment]
yes, it works now!
Thanks so much.

**Comment by ibesora** [comment]
Closing this then!
