### ISSUE TITLE
Problems with the visibility check

### ISSUE THREAD

**Issue by ibesora** [ibesora/vt-optimizer#13]
@ibesora I'm still having problems with the visibility check. It looks like later uses of a layer overwrite earlier ones resulting in removing to much source layers.

_Originally posted by @indus in https://github.com/ibesora/vt-optimizer/issues/12#issuecomment-1025648314_

**Comment by ibesora** [comment]
@indus , I'll take a look at it later this week.
Can you provide a repro example?
Thanks!

**Comment by indus** [comment]
@ibesora 
I have made a repo that shows the problems. https://github.com/indus/-vt-optimizer_issue13

I produced a [tiny mbtiles](https://github.com/indus/-vt-optimizer_issue13/blob/main/munich.mbtiles) file with only a [single point](https://github.com/indus/-vt-optimizer_issue13/blob/main/munich.geojson) for z0-4 in it.
Then there are 3 styles that should get used for optimization. When a layer is only used a single time I get correct results, but not when I use a layer in the mbtiles files more then once in the stylesheet: https://github.com/indus/-vt-optimizer_issue13/blob/main/style.json
You can find the results directly in the [README](https://github.com/indus/-vt-optimizer_issue13#test-3-stylejson-x) but I have also included the the (incorrect) optimized mbtiles.

**Comment by ibesora** [comment]
This should be fixed with https://github.com/ibesora/vt-optimizer/commit/b13107dcd4e15d9a18c7444ddf1efc986a457e00
@indus Thank you very much for your awesome repo. As you said, when multiple layers were using the same source-layer, it was getting overwritten

**Comment by indus** [comment]
I have to thank you :-)Am 05.02.2022 20:03 schrieb Isaac Besora Vilardaga ***@***.***>:
This shoudl be fixed with b13107d
@indus Thank you very much for your awesome repo. As you said, when multiple layers were using the same source-layer, it was getting overwritten
