### ISSUE TITLE
npm install does not make executable available

### ISSUE THREAD

**Issue by aaime** [ibesora/vt-optimizer#6]
On a Linux Mint install, no js special setup (not a JS dev), running "npm install" produces no executable in the path (but no error reported, the build seems normal, downloads dependencies and the like). Checked, it should end up in "/usr/local/bin" (the npm prefix is "/usr/local") but there is nothing new in there. A few minutes later I've installer vt2geojson using a similar procedure, no issue.

**Comment by ibesora** [comment]
Hi Andrea, I've updated the tool (via  #7) so it creates the binary file like what vt2geojson does.
You should do `npm install` again to get the last changes. 
Tell me if something is not working for you.

**Comment by aaime** [comment]
Thanks for the fast feedback. Got updates, cleaned up the git checkout for good measure, but the install failed. On the console I can see:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.0.7
npm ERR! Linux 5.0.0-27-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/aaime/devel/vt-optimizer/node_modules/.staging/@types/prop-types-d5d42520
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/aaime/devel/vt-optimizer/node_modules/.staging/@types/prop-types-d5d42520' -> '/home/aaime/devel/vt-optimizer/node_modules/tap/node_modules/@types/prop-types'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/aaime/devel/vt-optimizer/node_modules/.staging/@types/prop-types-d5d42520' -> '/home/aaime/devel/vt-optimizer/node_modules/tap/node_modules/@types/prop-types'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aaime/devel/vt-optimizer/npm-debug.log
```
Here is the debug file:
[npm-debug.log](https://github.com/ibesora/vt-optimizer/files/3614163/npm-debug.log)
