### ISSUE TITLE
Error: incorrect header check at Zlib.zlibOnError

### ISSUE THREAD

**Issue by iBinh** [ibesora/vt-optimizer#9]
command: 
`node --max-old-space-size=16386 index.js -m ../tiles/input.mbtiles -s ../style.json -o files/output.mbtiles`

![Screen Shot 2019-12-17 at 17 09 32](https://user-images.githubusercontent.com/13776018/70986282-331d0080-20f0-11ea-9861-6463d79b3de2.png)

**Comment by ibesora** [comment]
Hi!
Can you please provide an example of the VT file you are using? It seems it might not be compressed but I have yet to find one that it isn't.
Thanks!

**Comment by iBinh** [comment]
Update: I compressed mbtiles cause error

**Comment by ibesora** [comment]
Sorry, can you be more specific about what happened? 
I hadn't had time to look at the issue and I want to make sure it's something I do control.
Thanks!

**Comment by iBinh** [comment]
I use `tippecanoe` with `-pC` options to create mbtiles from geojson. This will compress tiles and causes error

**Comment by ibesora** [comment]
`tippecanoe -pC` disables compression, not enables it.
Will add a check so it doesn't crash when tiles are not compressed
Thanks for the info!
